### ISSUE TITLE
BUG with function flatten() | Undefined index: ownCloudGroups

### ISSUE THREAD

**Issue by ullriti** [pulsejet/nextcloud-oidc-login#41]
Hi,

iam using the following versions:
- Nextcloud 18.0.6
- OpenID Connect Login 1.5.0

And Keycloak as SSO Provider.
The Login with Keycloak and Nextcloud works but during the Login i´ve got the following warning in the log:

`{"reqId":"ceeE2yBX0xK87KXRVXqa","level":3,"time":"2020-06-19T12:12:40+00:00","remoteAddr":"192.168.112.1","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/oidc_login/oidc?state=b7c45a787253894a6bb0e1df74ce321d&session_state=0a567274-8048-4fc9-ae83-8d7d5fe8b550&code=5440e5f7-6e33-42f8-87d8-f44af9b8ff95.0a567274-8048-4fc9-ae83-8d7d5fe8b550.fe534e0a-301d-4257-a945-d2614f9d5b8f","message":"Undefined index: ownCloudGroups at /var/www/html/apps/oidc_login/lib/Controller/LoginController.php#284","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36","version":"18.0.6.0"} `
Keycloak Access Token looks like this:

```
{
  [...]
  "scope": "openid nextcloud",
  "ownCloudGroups": [
    "Test-Group",
    "secondTestGroup"
  ],
  "name": "test user",
  "preferred_username": "test",
  "email": "test@example.com"
}
```

In the Nextcloud config.php i defined:

```
[...] 
'oidc_login_attributes' =>
array (  
'id' => 'preferred_username', 
'name' => 'name',
'mail' => 'email', 
),
'oidc_login_use_external_storage' => false,
'oidc_login_scope' => 'openid nextcloud',
'oidc_login_proxy_ldap' => false,
'oidc_login_disable_registration' => false,
'oidc_login_redir_fallback' => true,
'oidc_login_tls_verify' => true,
```

Both groups are present in Nextcloud.

**Comment by pulsejet** [comment]
https://github.com/pulsejet/nextcloud-oidc-login/commit/1ebc0d1bd6be5cda004310150e9d3a11bc6af4e0 should fix the warning, but there might be something else going on here as the key is present in your access token.

**Comment by ullriti** [comment]
I reinstalled the plugin and configured a new Client in Keycloak. but the problem is still the same.

**Comment by ullriti** [comment]
I added a print_r($this->flatten($profile) to the LoginController.php:

The output of my test user show the attribute **ownCloudGroups_0**:
`Array ( [name] => Test Nutzer [sub] => 1d4a0c96-3c9c-415c-a294-4c9494d69e84 [preferred_username] => testuser [ownCloudGroups_0] => testGroup [email] => testuser@example.de ) `

Then i changed my configuration by adding:
```
'oidc_login_attributes' =>
array (  
   'id' => 'preferred_username', 
   'name' => 'name',
   'mail' => 'email', 
   'groups' => 'ownCloudGroups_0',
),
```

Then it works! But i dont think its right that the parameter is _ownCloudGroups_0_

So i tested with another user, which are in 2 groups.
I detected that the user was only added to the first group, The other groups were ignored. 
But both groups exists.

**Comment by pulsejet** [comment]
Very silly on my part. v1.5.1 should fix this by not flattening attributes specified in the config.
